// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_APP_SUPABASE_URL || "https://pmmdhslodtbwyxoatnrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_APP_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtbWRoc2xvZHRid3l4b2F0bnJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1ODQzOTEsImV4cCI6MjA2MzE2MDM5MX0.y8Y20mNpmzugAYQq-EhVYcrdMs7Xcg-5CbqNvc1p5O8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);